name: Documentation

on:
  pull_request:
    paths:
    - './include/*.h'

jobs:
  build-documentation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
          doxyfile-path: ./doxygen/Doxyfile
          working-directory: .
