name: Doxygen Generator

on:
  push:
    paths:
    - include/*.h
    branches:
    - main

jobs:
  generate-documentation:
    runs-on: ubuntu-latest

    env:
      DEFAULT_BRANCH: main

    steps:
    - uses: actions/checkout@v2
      with:
        ref: $DEFAULT_BRANCH

    - name: Generate doxygen
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        doxyfile-path: doxygen/Doxyfile
        working-directory: .

    - name: commit & push
      id: commit_push
      env:
        OUTPUT_DIR: docs
        INCLUDE_DIR: include
      run: |
        last_commit_user_name=`git log -1 --pretty=format:"%an" $INCLUDE_DIR`
        last_commit_user_email=`git log -1 --pretty=format:"%ae" $INCLUDE_DIR`
        last_commit_short_id=`git log -1 --pretty=format:"%h" $INCLUDE_DIR`
        branch_name=feature/update-docs-${last_commit_short_id}
        git switch -c "$branch_name"
        git add -N "$OUTPUT_DIR"
        if ! git diff --exit-code --quiet
        then
          git config user.name "$last_commit_user_name"
          git config user.email "$last_commit_user_email"
          git add "$OUTPUT_DIR"
          git commit -m "Update docs"
          git push -f origin $branch_name
        fi
        echo ::set-output name=commit_user::$last_commit_user_name
        echo ::set-output name=branch_name::$branch_name

    - name: Install hub
      run: |
        sudo apt install hub
    - name: Create pull request
      env:
        GITHUB_USER: ${{ steps.commit_push.outputs.commit_user }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set +e
        curl \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${GITHUB_TOKEN}" \
          "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls?state=open&sort=updated&direction=desc" \
          | jq '.[].head.ref' | grep ${{ steps.commit_push.outputs.branch_name }}
        ret="$?"
        set -e
        if [ $ret -ne 0 ]; then
          hub pull-request -m "Update docs" -b $DEFAULT_BRANCH
        fi
