name: Documentation

on:
  pull_request:
    paths:
    - 'include/*.h'

jobs:
  build-documentation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.head_ref}}

    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
          doxyfile-path: doxygen/Doxyfile
          working-directory: .

    - name: commit & push
      run: |
          OUTPUT_DIR="docs"
          branch_name="feature/update-docs-`date "+%Y-%m%d-%H%M-%S"`"
          git switch -c $branch_name
          git add -N "$OUTPUT_DIR"
          if ! git diff --exit-code --quiet
          then
            git config user.name github-actions
            git config user.email actions@github.com
            git add "$OUTPUT_DIR"
            git commit -m "Update docs"
            git push origin $branch_name
          fi
