name: Documentation

on:
  pull_request:
    paths:
    - 'include/*.h'

jobs:
  build-documentation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.head_ref}}

    - name: Generate doxygen
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
          doxyfile-path: doxygen/Doxyfile
          working-directory: .

    - name: commit & push
      id: commit_push
      run: |
          last_commit_user_name=`git log -1 --pretty=format:"%an"`
          last_commit_user_email=`git log -1 --pretty=format:"%ae"`
          OUTPUT_DIR="docs"
          git fetch origin main
          git switch -c main
          branch_name="feature/update-docs-`date "+%Y-%m%d-%H%M-%S"`"
          git switch -c "$branch_name"
          git add -N "$OUTPUT_DIR"
          if ! git diff --exit-code --quiet
          then
            # git config user.name xxx
            # git config user.email xxx
            git config user.name "$last_commit_user_name"
            git config user.email "$last_commit_user_email"
            git add "$OUTPUT_DIR"
            git commit -m "Update docs"
            git push origin $branch_name
            git branch -D "$default_tmp_branch"
          fi
          echo ::set-output name=commit_user::$last_commit_user_name

    - name: Install hub
      run: |
        sudo apt install hub

    - name: Create pull request
      env:
        GITHUB_USER: ${{ steps.commit_push.outputs.commit_user }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        hub pull-request -m "Update docs" -b ${{ github.event.repository.default_branch }}
